sudo: false

language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - g++-4.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi

os:
  - osx
  - linux

node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"

install:
  - npm -g i npm@latest
  - npm i --build-from-source

scripts:
  - npm test
  - npm run deploy
