sudo: false

language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - g++-4.8

env:
  - CXX=g++-4.8

os:
  - osx
  - linux

node_js:
  - stable
  - 7
  - 6
  - 5
  - 4
  - 0

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - npm install --build-from-source

# Post-install test scripts.
scripts:
  - npm test
  - npm run deploy
