sudo: false

language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - g++

os:
  - osx
  - linux

node_js:
  - stable
  - 7
  - 6
  - 5
  - 4

install:
  - npm -g i npm@latest
  - npm i --build-from-source

scripts:
  - npm test
  - npm run deploy
