sudo: false

language: node_js

env:
  - CXX=g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - g++-4.8

os:
  - osx
  - linux

node_js:
  - stable
  - 7
  - 6
  - 5
  - 4
  - 0

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - npm i --build-from-source

scripts:
  - npm test
  - npm run deploy
