version: "{build}"
build: off
skip_tags: true

environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -g i npm@latest
  - npm i --ignore-scripts
  - npm run rebuild

test_script:
  - npm test

on_success:
  - npm run deploy