version: "{build}"
skip_branch_with_pr: true
skip_tags: true
build: off

environment:
  matrix:
    - nodejs_version: stable
    - nodejs_version: 7
    - nodejs_version: 6
    - nodejs_version: 5

platform:
  - x64
  - x86

# Install scripts. (runs after repo cloning)
install:
  # install Node.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # Get the latest stable version of npm
  - npm -g i npm@latest
  # install modules
  - appveyor-retry call npm install --build-from-source

# to run your custom scripts instead of automatic tests
test_script:
  - IF %nodejs_version%==stable cmake -H. -Bbuild -G"Visual Studio 12" -DCMAKE_INSTALL_PREFIX="path/to/install"
  - IF %nodejs_version%==stable cmake --build build --config Release --target install
  - npm test

artifacts:

  # pushing a single file
  - path: build
    name: OpenCC
    type: zip

# to run your custom scripts instead of provider deployments
deploy_script:
  - npm run deploy
