version: "{build}"
skip_branch_with_pr: true
skip_tags: true
build: off

environment:
  matrix:
    - nodejs_version: stable
    - nodejs_version: 7
    - nodejs_version: 6
    - nodejs_version: 5
    - nodejs_version: 4

platform:
  - x64
  - x86

# scripts that run after cloning repository
install:
  # install Node.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - npm install --build-from-source

# to run your custom scripts instead of automatic tests
test_script:
  - npm test

# to run your custom scripts instead of provider deployments
deploy_script:
  - npm run deploy
